name: build focal backports packages

env:
    DOCKER_PATH: kaylor/focal_humble_env

on: 
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/build-focal-backports.yml.yml"
      - "packages.list"
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [arm64]
    
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3
    
    - name: Build
      run: |
        if [ ${{ matrix.architecture}} == arm64 ]; then
          echo Architecture is ${{ matrix.architecture}}
          docker run --privileged --rm tonistiigi/binfmt --install all
          docker pull ${DOCKER_PATH}:${{ matrix.architecture }}_compile_base1.1
        fi
        docker run --rm -v ${PWD}:/root/ws ${DOCKER_PATH}:${{ matrix.architecture }}_compile_base1.1 sh -c "cd /root/ws && bash ./build.sh"
        tree deb_packages

    - name: upload artifact debian packages
      uses: actions/upload-artifact@v3
      with:
        name: deb
        path: ./deb_packages
